"""
orbit_index_null.py -- Paper 101 v3.1, Mr A objection (1): re-run the section 5.3
mass-ratio null against the family of 2I SUBGROUP ORBIT INDICES [2I:H] = 120/|H|,
in place of the flat declared integer set.

Pre-registration (locked, seed 42, Pattern 75):
  STEP 1  Enumerate ALL subgroups of 2I from the explicit 120-element group
          (Cayley table; every subgroup of 2I is 2-generated, so closures of all
          singletons and pairs find every subgroup -- this makes the "not realised"
          claims for orders 15/30/40/60 a computed result, not an assertion).
          Report the realised subgroup-order set and the realised index set
          {120/|H|}.
  STEP 2  Repeat the section 5.3 enumeration EXACTLY (same surviving 2I spectrum
          l<=120, same 5 mass-ratio targets, same +/- operation, same 0.01% window)
          but draw the correction from the realised orbit-index set of STEP 1.
  STEP 3  Report: how many orbit indices fall inside the old swept range (<=168);
          whether 1848-12 is still the UNIQUE survivor; and if 12 is not unique,
          the null measured spectral sparsity, not the orbit-index mechanism.

Mr A's charge: if many [2I:H] fall in the swept range and several produce hits,
"exactly one survivor" was measuring the sparse spectrum, not the privilege of the
orbit-index mechanism. Fizz's on-record prediction: 12 stays the unique survivor on
m_p/m_e because survival is spectrum-driven. We report the bare count regardless.

Exact arithmetic for the group theory (Q(sqrt5) quaternions); the final mass-ratio
comparison is the only floating-point step (identical to section 5.3).

Run: python orbit_index_null.py
"""

import csv
import random

from vertex_index_2I import build_2I, qmul, qconj, QID, order_of
from massratio_null import TARGETS, OPERATIONS, WINDOWS, PRIMARY, survivors_at
from spectrum import surviving_levels

SEED = 42
random.seed(SEED)

# ---------------------------------------------------------------------------
# STEP 1 -- subgroup enumeration via an integer Cayley table (exact, complete)
# ---------------------------------------------------------------------------

def build_cayley(G):
    idx = {g: i for i, g in enumerate(G)}
    n = len(G)
    mult = [[0] * n for _ in range(n)]
    for i, a in enumerate(G):
        for j, b in enumerate(G):
            mult[i][j] = idx[qmul(a, b)]
    e = idx[QID]
    return idx, mult, e

def closure(gens, mult, e):
    """Subgroup generated by gens (list of int indices), as a frozenset of ints."""
    elems = {e}
    elems.update(gens)
    frontier = list(elems)
    while frontier:
        new = []
        for a in frontier:
            for g in gens:
                p = mult[a][g]
                if p not in elems:
                    elems.add(p)
                    new.append(p)
        frontier = new
    return frozenset(elems)

def all_subgroups(G):
    idx, mult, e = build_cayley(G)
    n = len(G)
    cyc = [closure([i], mult, e) for i in range(n)]
    subs = set(cyc)                       # all cyclic subgroups
    for i in range(n):
        for j in range(i + 1, n):
            if j in cyc[i]:               # <j> already inside <i>: same closure
                continue
            subs.add(closure([i, j], mult, e))
    return subs

# ---------------------------------------------------------------------------

def main():
    print("=" * 72)
    print("Paper 101 v3.1 -- orbit-index null (Mr A objection 1)")
    print("=" * 72)

    G = build_2I()
    assert len(G) == 120
    print(f"\n|2I| = {len(G)} (exact icosian quaternions)")

    print("\n" + "-" * 72)
    print("STEP 1 -- realised subgroups of 2I and their orbit indices")
    print("-" * 72)
    subs = all_subgroups(G)
    from collections import Counter
    order_counts = Counter(len(H) for H in subs)
    realised_orders = sorted(order_counts)
    print(f"distinct subgroups found      : {len(subs)}")
    print(f"realised subgroup ORDERS      : {realised_orders}")
    print("per-order subgroup counts     : "
          + ", ".join(f"{o}:{order_counts[o]}" for o in realised_orders))

    all_divisors = [d for d in range(1, 121) if 120 % d == 0]
    not_realised = [d for d in all_divisors if d not in order_counts]
    print(f"divisors of 120 NOT a subgroup order: {not_realised}  "
          f"(computed, not asserted)")

    realised_indices = sorted({120 // o for o in realised_orders})
    print(f"\nrealised ORBIT-INDEX set [2I:H] = 120/|H| : {realised_indices}")
    assert 12 in realised_indices, "the vertex index [2I:C10]=12 must be present"

    # discriminating count: how many fall in the old swept range (<=168)
    in_range = [c for c in realised_indices if c <= 168]
    print(f"orbit indices inside the old swept range (<=168): "
          f"{len(in_range)} of {len(realised_indices)}  -> {in_range}")

    # ---------------------------------------------------------------------
    print("\n" + "-" * 72)
    print("STEP 2 -- the section 5.3 null, corrections drawn from the orbit-index set")
    print("-" * 72)
    CORR = realised_indices
    levels_raw, _ = surviving_levels(120)
    levels = [(l, lam) for (l, lam, mult) in levels_raw if l > 0]
    combos = []
    for (l, lam) in levels:
        for (opsym, opsign) in OPERATIONS:
            for c in CORR:
                combos.append((l, lam, opsym, c, lam + opsign * c))
    n_full = len(combos) * len(TARGETS)
    print(f"surviving levels (l>0)        : {len(levels)}")
    print(f"corrections (orbit indices)   : {len(CORR)}  {CORR}")
    print(f"operations                    : {len(OPERATIONS)} (+/-)")
    print(f"targets                       : {len(TARGETS)}  {list(TARGETS)}")
    print(f"combination count             : {n_full}  "
          f"(= {len(levels)} x {len(CORR)} x 2 x {len(TARGETS)})")

    rows = []
    for window in WINDOWS:
        res = survivors_at(combos, window)
        total = sum(len(v) for v in res.values())
        print(f"\nWINDOW {window*100:.3f}%  -- total survivors: {total}")
        for t in TARGETS:
            hits = sorted(res[t], key=lambda r: r[5])
            if not hits:
                print(f"  {t:10s}: 0")
            else:
                print(f"  {t:10s}: {len(hits)}")
                for (l, lam, opsym, c, value, rel) in hits:
                    print(f"      l={l:3d} lambda={lam:6d} {opsym}{c:<3d} "
                          f"= {value:9.3f}   rel={rel*100:.4f}%")
                    rows.append((f"{window*100:.3f}%", t, l, lam, opsym, c,
                                 value, f"{rel:.3e}"))

    # ---------------------------------------------------------------------
    print("\n" + "=" * 72)
    print("STEP 3 -- the discriminating verdict")
    print("=" * 72)
    res = survivors_at(combos, PRIMARY)
    n_total = sum(len(v) for v in res.values())
    per_target = {t: len(res[t]) for t in TARGETS}
    print(f"primary window {PRIMARY*100:.3f}%  total survivors: {n_total}")
    for t in TARGETS:
        print(f"  {t:10s}: {per_target[t]}")

    # is 1848-12 still the unique survivor overall?
    # survivor tuple s = (target, l, lambda, opsym, correction, value, rel)
    survivors = [(t,) + tuple(h) for t in TARGETS for h in res[t]]
    is_1848_12 = [s for s in survivors
                  if s[2] == 1848 and s[3] == "-" and s[4] == 12]
    unique_overall = (n_total == 1)
    twelve_unique_on_mpe = (per_target["m_p/m_e"] == 1
                            and len(is_1848_12) == 1)
    print(f"\n1848-12 present as a survivor          : "
          f"{'YES' if is_1848_12 else 'NO'}")
    print(f"exactly ONE survivor overall           : "
          f"{'YES' if unique_overall else 'NO'}")
    print(f"12 is the UNIQUE orbit index that hits  : "
          f"{'YES' if twelve_unique_on_mpe and unique_overall else 'NO'}")
    print()
    if unique_overall and is_1848_12:
        print("VERDICT: the null SURVIVES the change of generative process. Even when")
        print("corrections are restricted to genuine 2I orbit indices, 1848-12=1836 on")
        print("m_p/m_e is the unique survivor at 0.01%. The result was NOT an artefact of")
        print("the flat integer set: clause (c) keeps its null support (Mr A objection 1")
        print("answered in the affirmative for clause (c)).")
    else:
        print("VERDICT: 12 is NOT the unique survivor among orbit indices. The 'exactly")
        print("one survivor' was measuring SPECTRAL SPARSITY, not the orbit-index")
        print("mechanism. Clause (c) keeps its mechanism but LOSES the null's support;")
        print("the section 5.1 box must say so. >>> FLAG TO CinC IMMEDIATELY. <<<")
    print("=" * 72)

    with open("orbit_index_matches.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["window", "target", "l", "lambda", "op", "correction",
                    "value", "rel"])
        w.writerows(rows)
    print("\nwrote orbit_index_matches.csv")


if __name__ == "__main__":
    main()
